name: Kubernetes Deploy

on:
  push:
    branched:
      - k8s-testing

jobs:
  deploy:
    runs-on: self-hosted


    steps:

      - name: Chekout Code
        uses: actions/checkout@v3

      - name: Configure Minikube Docker
        run: |
          eval $(minikube docker-env)
          docker build --no-cache -t devops-cicd-app-app:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment cicd-app

